---
name: Continuous Integration
on:
  schedule:
    - cron: "5 * * * *"
jobs:
  normal-build:
    name: Normal Test Config ${{ matrix.cfg }}
    runs-on: ubuntu-20.04
    env:
      DEVELOPER: 1
      VALGRIND: 0
      EXPERIMENTAL_FEATURES: 0
      COMPAT: 1
    strategy:
      fail-fast: false
      matrix:
        include:
            - CFG: "cross-s390x"
              ARCH: s390x
              TARGET_HOST: s390x-linux-gnu
            - CFG: "cross-i386"
              ARCH: i386
              TARGET_HOST: i686-linux-gnu
            - CFG: "cross-mips64"
              ARCH: mips64
              TARGET_HOST: mips64-linux-gnuabi64
            - CFG: "cross-arm32v7"
              ARCH: arm
              TARGET_HOST: arm-linux-gnueabihf
            - CFG: "cross-arm64"
              ARCH: aarch64
              TARGET_HOST: aarch64-linux-gnu
            - CFG: "cross-mips32"
              ARCH: mips
              TARGET_HOST: mips-linux-gnu
            - CFG: "cross-powerpc"
              ARCH: ppc
              TARGET_HOST: powerpc-linux-gnu
            - CFG: "cross-powerpc64"
              ARCH: ppc64
              TARGET_HOST: powerpc64-linux-gnu
            - CFG: "cross-riscv64"
              ARCH: riscv64
              TARGET_HOST: riscv64-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Checkout ln source
        run: git clone --progress https://github.com/ElementsProject/lightning.git

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          bash -x .github/scripts/setup.sh

      - name: Build
        env:
          VALGRIND: ${{ matrix.VALGRIND }}
          DEVELOPER: ${{ matrix.DEVELOPER }}
          EXPERIMENTAL_FEATURES: ${{ matrix.EXPERIMENTAL_FEATURES }}
          EXPERIMENTAL_DUAL_FUND: ${{ matrix.EXPERIMENTAL_DUAL_FUND }}
          COMPILER: ${{ matrix.COMPILER }}
          ARCH: ${{ matrix.ARCH }}
          TARGET_HOST: ${{ matrix.TARGET_HOST }} 
          COMPAT: ${{ matrix.COMPAT }}
          FUZZING: ${{ matrix.FUZZING }}
          PYTEST_PAR: ${{ matrix.PYTEST_PAR }}
          PYTEST_OPTS: ${{ matrix.PYTEST_OPTS }}
          NETWORK: ${{ matrix.NETWORK }}
          TEST_CHECK_DBSTMTS: ${{ matrix.TEST_CHECK_DBSTMTS }}
          TEST_CMD: ${{ matrix.TEST_CMD }}
          TEST_GROUP_COUNT: ${{ matrix.TEST_GROUP_COUNT }}
          TEST_GROUP: ${{ matrix.TEST_GROUP }}
          TEST_DB_PROVIDER: ${{ matrix.DB }}
        run: |
          cd lightning
          bash -x ../.github/scripts/build.sh
