---
name: Mac OS M1 pytest
on:
  #push:
  #  branches:
  #    - "master"
  schedule:
    - cron: "0 1 * * *"
jobs:
  smoke-test:
    name: Smoke Test macOS M1
    runs-on: macOS
    env:
      DEVELOPER: 1
      VALGRIND: 0
      EXPERIMENTAL_FEATURES: 1
      COMPAT: 0
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Checkout cln source
        run: git clone --progress https://github.com/ElementsProject/lightning.git

      - name: Install dependencies
        run: |
          cd lightning
          export PATH="/usr/local/opt:/Users/runner/.local/bin:/Users/runner/Library/Python/3.10/bin:$PATH"

          export BITCOIN_VERSION=0.20.1
          arch -arm64 brew install wget autoconf automake libtool python@3.10 gmp gnu-sed gettext libsodium

          (
            cd /tmp/
            wget https://storage.googleapis.com/c-lightning-tests/bitcoin-$BITCOIN_VERSION-osx64.tar.gz -O bitcoin.tar.gz
            tar -xvzf bitcoin.tar.gz
            sudo mv bitcoin-$BITCOIN_VERSION/bin/* /usr/local/bin
          )

          arch -arm64 python3.10 -m pip install -U --user poetry wheel pip
          arch -arm64 python3.10 -m poetry install
          arch -arm64 python3.10 -m pip install -U --user mako
          
          ln -s /usr/local/Cellar/gettext/0.20.1/bin/xgettext /usr/local/opt

      - name: Build
        env:
          VALGRIND: ${{ matrix.VALGRIND }}
          DEVELOPER: ${{ matrix.DEVELOPER }}
          EXPERIMENTAL_FEATURES: ${{ matrix.EXPERIMENTAL_FEATURES }}
          COMPILER: ${{ matrix.COMPILER }}
          COMPAT: ${{ matrix.COMPAT }}
          PYTEST_PAR: ${{ matrix.PYTEST_PAR }}
          PYTEST_OPTS: ${{ matrix.PYTEST_OPTS }}
          NO_PYTHON: ${{ matrix.NO_PYTHON }}
          COPTFLAGS: ${{ matrix.COPTFLAGS }}
          NETWORK: ${{ matrix.NETWORK }}
          TEST_CMD: ${{ matrix.TEST_CMD }}
          TEST_GROUP_COUNT: ${{ matrix.TEST_GROUP_COUNT }}
          TEST_GROUP: ${{ matrix.TEST_GROUP }}
        run: |
          export PATH="/usr/local/opt:/Users/runner/.local/bin:/Users/runner/Library/Python/3.10/bin:/usr/local/opt:$PATH"
          export LDFLAGS="-L/usr/local/opt/sqlite/lib"
          export CPPFLAGS="-I/usr/local/opt/sqlite/include"

          cat << EOF > pytest.ini
          [pytest]
          addopts=-p no:logging --color=yes --timeout=600 --timeout-method=thread --test-group-random-seed=42 --junitxml=report.xml --json-report --json-report-file=report.json --json-report-indent=2
          markers =
              slow_test: marks tests as slow (deselect with '-m "not slow_test"')
          EOF

          arch -arm64 python3.10 -m poetry run ./configure
          arch -arm64 python3.10 -m poetry run make
