---
name: WIN pytest
on:
  push:
    branches:
      - "master"
jobs:
  smoke-test:
    name: Smoke Test Win
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      PYTHONIOENCODING: "utf-8"
    steps:
    - uses: actions/checkout@master
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git base-devel autoconf automake libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip mingw-w64-x86_64-zlib msys2-runtime-devel mingw-w64-x86_64-gmp mingw-w64-x86_64-python-poetry mingw-w64-x86_64-python3-cffi mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-python3-cryptography mingw-w64-x86_64-python3-mako mingw-w64-x86_64-libsodium mingw-w64-x86_64-gettext
    - name: Checkout cln source
      run: git clone --progress https://github.com/ElementsProject/lightning.git
    - name: Build 
      run: |
        cd lightning
        #echo "C:\Users\runneradmin\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        #echo "C:\Users\runneradmin\.local\bin" >> $GITHUB_PATH
        poetry config virtualenvs.create false --local
        #poetry install
        ./configure --enable-static --disable-rust
        make -j
 
