---
name: WIN pytest
on:
  push:
    branches:
      - "master"
jobs:
  smoke-test:
    name: Smoke Test macOS M1
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      PYTHONIOENCODING: "utf-8"
    steps:
    - uses: actions/checkout@master
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: base-devel autoconf automake libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip mingw-w64-x86_64-zlib msys2-runtime-devel
    - name: Build 
      run: |
        cd lightning
        bash -x ../.github/scripts/build.sh
